
#include <disk_management/disk_management.hpp>
#include <sd_device_hardware_detector.hpp>

#include <disk_management/localization>

// Generated by localization_embed_catalogs() (see CMakeLists.txt). Registers
// the embedded en/ja stage catalogs with the localization engine.
extern void localization_register_disk_management_catalogs();

// Composition root: trigger singleton construction so methods self-register.
// With static libraries, the linker drops translation units that don't resolve
// any undefined symbols, so auto-registration alone is not sufficient.
#include <secure_erase.hpp>
#include <secure_erase_enhanced.hpp>
#include <nist_800.hpp>
#include <nist_800_adv.hpp>
#include <zero_write.hpp>
#include <random_write.hpp>
#include <random_zero_write.hpp>
#include <nsa.hpp>
#include <bit_toggle.hpp>
#include <dod_5220_28_m.hpp>
#include <dod_5220_22_m.hpp>
#include <afssi_5020.hpp>
#include <navso_p5239_26_mfm.hpp>
#include <navso_p5239_26_rll.hpp>
#include <bsi_vsitr.hpp>
#include <gutmann.hpp>

namespace {

void ensureMethodsRegistered() {
    [[maybe_unused]] static bool registered = [] {
        NIST800::shared();
        NIST800Adv::shared();
        SecureErase::shared();
        EnhancedSecureErase::shared();
        ZeroWrite::shared();
        RandomWrite::shared();
        RandomZeroWrite::shared();
        NSA::shared();
        BitToggle::shared();
        DoD522028M::shared();
        DoD522022M::shared();
        AFSSI5020::shared();
        NAVSOP523926MFM::shared();
        NAVSOP523926RLL::shared();
        BSIVSITR::shared();
        Gutmann::shared();
        return true;
    }();
}

void ensureLocalizationRegistered() {
    [[maybe_unused]] static bool registered = [] {
        localization_register_disk_management_catalogs();
        return true;
    }();
}

} // anonymous namespace

namespace DiskManagement {

const std::vector<std::reference_wrapper<DiskSanitizationInterface>>& methods() {
    ensureMethodsRegistered();
    return SanitizationMethodRegistry::instance().methods();
}

void setLocale(const std::string& code) {
    ensureLocalizationRegistered();
    Localization::setLocale(code);
}

std::string locale() {
    ensureLocalizationRegistered();
    return Localization::locale();
}

std::vector<std::unique_ptr<Disk>> fetchDisks() {
    SDDeviceHardwareDetector detector;
    return detector.fetchDisks();
}

std::vector<std::unique_ptr<Disk>> fetchDisks(HardwareDetector& detector) {
    return detector.fetchDisks();
}

} // namespace DiskManagement
