# localization_embed_catalogs(<target> <locale> <file> [<locale> <file> ...])
#
# Embeds one or more `key = value` catalog files directly into <target> at
# build time, so there are no runtime files to locate. It generates a single
# C++ source defining:
#
#     void localization_register_<target>_catalogs();
#
# which, when called, registers every (locale, file) pair with the engine via
# Localization::registerCatalog(). The composition root of <target> should
# declare this function `extern` and call it once. An explicit call (rather
# than static-init) keeps the generated translation unit from being dropped by
# the static linker.
#
# <target> must expose the vendored localization header on its include path so the
# generated source can include <disk_management/localization>.
function(localization_embed_catalogs target)
    set(pairs ${ARGN})
    list(LENGTH pairs pairs_len)
    math(EXPR is_even "${pairs_len} % 2")
    if(NOT is_even EQUAL 0 OR pairs_len EQUAL 0)
        message(FATAL_ERROR
            "localization_embed_catalogs: expected (locale file) pairs, got: ${pairs}")
    endif()

    set(body "")
    set(i 0)
    while(i LESS pairs_len)
        list(GET pairs ${i} locale)
        math(EXPR j "${i} + 1")
        list(GET pairs ${j} file)

        if(NOT EXISTS "${file}")
            message(FATAL_ERROR "localization_embed_catalogs: file not found: ${file}")
        endif()

        # Re-run CMake configure if a catalog file changes so the embedded copy
        # stays in sync.
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${file}")

        file(READ "${file}" contents)
        string(APPEND body
            "    Localization::registerCatalog(\"${locale}\", R\"WPLOC(\n${contents})WPLOC\");\n")

        math(EXPR i "${i} + 2")
    endwhile()

    set(generated "${CMAKE_CURRENT_BINARY_DIR}/${target}_localization_catalogs.cpp")
    file(WRITE "${generated}"
"// Auto-generated by localization_embed_catalogs(). Do not edit.\n"
"#include <disk_management/localization>\n"
"\n"
"void localization_register_${target}_catalogs() {\n"
"${body}"
"}\n")

    target_sources(${target} PRIVATE "${generated}")
endfunction()
